### ISSUE TITLE
Getting stuck with deployment on gh-pages.

### ISSUE THREAD

**Issue by guyandtheworld** [luanorlandi/luanorlandi.github.io#1]
Okay, first of all, this is one of the best static page portfolios I've come across! It's simple and looks amazing.  

I'm pretty sure I'm facing this issue because of my unfamiliarity with React and Gatsby. I'm not able to properly deploy this site for myself at https://isht3.github.io/

When I run `gatsby serve` on my local server, everything works smooth and all goes well. But after I push it to the master branch it just shows the README file as you can see here https://isht3.github.io/

Do I need to deploy it from some other branch or change any settings? Any directions on how to do this properly is much appreciated. Thanks a lot!

**Comment by luanorlandi** [comment]
Hello @isht3, thanks for your words, I appreciate it!

Sorry for the late response, I was on vacation. I just checked your website: https://isht3.github.io/, everything looks pretty well, I think you managed to deploy your site, nice!

Just a reminder, for any repository with the name like: username.github.io, the master branch should have the builded files, if GitHub can't find a index.html, it will try to use the README.md file, also processing it for a HTML page. Other repositories works in the same way, but with gh-pages branch.

I will close the issue for now. Let me know if you need help again.

**Comment by guyandtheworld** [comment]
@luanorlandi Thanks! That's exactly what went wrong. I didn't have the built files. I still have some work to do on my page because I just hosted it by changing the name and a few other stuff but I still have a bit more work to do there. Hope you had a nice vacation!
